apiVersion: v1
kind: Service
metadata:
  name: portal-nt-service
  labels:
    app: portal-nt-service
spec:
  type: ClusterIP
  selector:
    app: portal-nt-dep
  ports:
  - port: 3051
    targetPort: 8080
