apiVersion: v1
kind: Service
metadata:
  name: portal-nsw-service
  labels:
    app: portal-nsw-service
spec:
  type: ClusterIP
  selector:
    app: portal-nsw-dep
  ports:
  - port: 3000
    targetPort: 8080    
